### ISSUE TITLE
텍스트 입력 기능 구현

### ISSUE THREAD

**Issue by woosung1223** [Team-Usay/usay-server#1]
- [ ] 텍스트 입력 기능을 구현한다.

**Comment by loveysuby** [comment]
@woosung1223 입력과 출력 기능이 #3 과 유사한 것 같기도 하고..? 

- `Client view`에서 대화 입력 기능에 의해 서버에 대화를 요청하고, (`대화 전송`)
- 서버의 service 로직에서 LLM Model의 입력으로 요청해야 해. (`프롬프트 파싱` > `모델 입력`값 전송)
  
이후 대화의 출력 기능은 서버의 `대화 수신` 기능에 의해 rendering 가능하다고 생각했는데, 이 부분에 대한 조율이 필요해보여.

만약 같은 의견이라면 #1, #2 의 요구사항을 `대화 전송/수신` 으로 보고 #3 에서 함께 반영할게 🌗

**Comment by woosung1223** [comment]
@loveysuby 

인정합니다. 서버에서 입출력에 대한 구분은 하지 않아도 될 거 같네요~

#1, #2 는 통합해서 #3과 함께 처리해주십쇼 🙇‍♂️
